# Generated by Django 4.1.1 on 2023-02-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_alerta', models.FloatField()),
                ('nivel_alarma', models.IntegerField()),
                ('estado_alarma', models.BooleanField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=30)),
                ('fecha_estad0', models.DateField()),
                ('min_valor', models.FloatField()),
                ('med_valor', models.FloatField()),
                ('max_valor', models.FloatField()),
                ('valor_critico', models.FloatField()),
                ('frecuencia', models.IntegerField()),
                ('irregularidades', models.TextField()),
                ('unidad_valor', models.CharField(max_length=10)),
                ('correos', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidas_tomadas', models.TextField()),
                ('fecha_de_la_medida', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Valor_Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('valor_en_porcentaje', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
