# Generated by Django 4.1.1 on 2023-02-21 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Indicadores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicador',
            old_name='fecha_estad0',
            new_name='fecha_estado',
        ),
        migrations.AddField(
            model_name='alarma',
            name='valor_de_indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Indicadores.valor_indicador'),
        ),
        migrations.AddField(
            model_name='medida',
            name='alarma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Indicadores.alarma'),
        ),
        migrations.AddField(
            model_name='medida',
            name='indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Indicadores.indicador'),
        ),
        migrations.AddField(
            model_name='valor_indicador',
            name='indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Indicadores.indicador'),
        ),
    ]
